apiVersion: apps/v1
kind: Deployment
metadata:
  name: socialmedia-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: socialmedia
  template:
    metadata:
      labels:
        app: socialmedia
    spec:
      containers:
        - name: socialmedia
          image: socialmedia:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "200m"
