  pipeline {
      agent any

      stages {
          stage('Checkout') {
              steps { checkout scm }
          }

          stage('Compile') {
              steps {
                  bat '''
                    docker run --rm ^
                      -v "%WORKSPACE%":/ws ^
                      -w /ws ^
                      maven:3.9-eclipse-temurin-21 mvn -B -V compile
                  '''
              }
          }

          stage('Test') {
              steps {
                  bat '''
                    docker run --rm ^
                      -v "%WORKSPACE%":/ws ^
                      -w /ws ^
                      maven:3.9-eclipse-temurin-21 mvn -B -V test
                  '''
              }
          }
      }

      post {
          always {
              junit '**/target/surefire-reports/*.xml'
          }
      }
  }