version: '3.8'

services:
  jenkins:
    build:
      context: .
      dockerfile: Jenkins-Dockerfile
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
    privileged: true
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false

volumes:
  jenkins_home:
