pipeline {
    agent any

    stages {
        stage('Diagnostics') {
            steps {
                bat '''
                  echo WORKSPACE: %WORKSPACE%
                  dir "%WORKSPACE%"
                  dir "%WORKSPACE%\devops1"
                '''
            }
        }

        stage('Build') {
            steps {
                bat '''
                  docker build -t flask-app -f "%WORKSPACE%\devops1\Dockerfile" "%WORKSPACE%\devops1"
                '''
            }
        }
        
        stage('Run') {
            steps {
                bat '''
                  docker rm -f demo || exit /B 0
                  docker run -d --name demo -p 5000:5000 flask-app
                '''
            }
        }
        
        stage('Test') {
            steps {
                bat '''
                  timeout /t 10 /nobreak > NUL
                  curl http://localhost:5000/ || echo Test failed
                '''
            }
        }
    }
}