pipeline {
    agent any

    environment {
        APP_NAME = 'flask-demo'
        IMAGE = "${env.DOCKERHUB_USER ?: 'local'}/${APP_NAME}"
        TAG   = "${env.BUILD_NUMBER}"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Unit Tests') {
    steps {
        sh '''
          set -euxo pipefail
          python3 --version
          pip3 --version

          # Install deps locally for Jenkins user
          python3 -m pip install --user --upgrade pip
          python3 -m pip install --user -r requirements.txt

          # Add ~/.local/bin to PATH so installed tools are found
          export PATH=$HOME/.local/bin:$PATH

          python3 -m pytest -q
        '''
    }
}


        stage('Build Image') {
            steps {
                sh """
                  set -euxo pipefail
                  docker build -t ${IMAGE}:${TAG} .
                  docker tag ${IMAGE}:${TAG} ${IMAGE}:latest
                """
            }
        }

        stage('Deploy (Run Container)') {
            steps {
                sh """
                  set -euxo pipefail
                  docker rm -f demo || true
                  docker run -d --name demo -p 5000:5000 ${IMAGE}:latest
                """
            }
        }

        stage('Smoke Test') {
            steps {
                sh '''
                  set -euxo pipefail
                  sleep 5
                  curl -fsS http://localhost:5000/ | tee smoke.json
                '''
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'smoke.json', onlyIfSuccessful: false
        }
    }
}
