version: "3.9"

services:
  litestar-api:
    build: .
    container_name: litestar-api
    ports:
      - "8000:8000"
    restart: always
    environment:
      - PYTHONUNBUFFERED=1

  jenkin:
    image: jenkins/jenkins:lts
    container_name: jenkin
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  jenkins_home:
