apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
stringData:
  mongo-user: monogouser  # plain text value, Kubernetes will base64 encode it
  mongo-password: monogopass  # plain text value, Kubernetes will base64 encode it
