apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-media-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: social-media-app
  template:
    metadata:
      labels:
        app: social-media-app
    spec:
      containers:
      - name: social-media-container
        image: social-media-app:latest
        ports:
        - containerPort: 4200
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 500m
