# Use the official Node.js image as the base image
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY angular-app/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY angular-app/ .

# Expose port 4200 for development server
EXPOSE 4200

# Start the development server
CMD ["npm", "start"]
