apiVersion: v1
kind: Service
metadata:
  name: apache-service
  labels:
    app: apache-server
spec:
  selector:
    app: apache-server
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: NodePort  # Use NodePort to access from host machine
